const DRUGS = [
  {
    "name": "Adenosine",
    "group": "Antiarrhythmics",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "6 mg → 6 mg → 12 mg",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Regular narrow-complex SVT\n• Diagnostic/therapeutic AV-nodal block in selected regular tachycardias",
    "contra": "• 2nd/3rd-degree AV block without pacemaker\n• Sick sinus/symptomatic bradycardia without pacemaker\n• Bronchospastic disease/asthma\n• Hypersensitivity",
    "monitor": "• Continuous ECG\n• HR and BP\n• Rhythm response",
    "pharm": "Purine nucleoside / AV nodal blocker",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "A1-receptor agonist → transient AV-nodal conduction block.",
    "side_effects": "• Transient AV block/bradycardia\n• Flushing/chest discomfort\n• Bronchospasm",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Amiodarone",
    "group": "Antiarrhythmics",
    "std": "LD: 150 mg/100 cc (p)\nMD: 450 mg/250 cc (p)",
    "conc": "300 mg/50 cc (c) — MD/LD",
    "dose": "LD: 150–300 mg over 30–60 min\nMD: 900 mg / 24 h\nSee PROCOR administration protocol",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Recurrent VF\n• Hemodynamically unstable VT\n• Shock-refractory VF / pulseless VT during cardiac arrest",
    "contra": "• Cardiogenic shock\n• Marked sinus bradycardia\n• 2nd/3rd degree AV block without functioning pacemaker\n• Hypersensitivity to amiodarone/components, including iodine\n• ⚠ Hypotension, bradycardia/AV block during IV infusion",
    "monitor": "• Continuous ECG / rhythm\n• HR and BP\n• QT/QTc\n• K⁺ / Mg²⁺\n• Liver function when clinically indicated",
    "pharm": "Class III antiarrhythmic",
    "std_en": "LD: 150 mg / 100 mL (P) — D5W\nMD: 450 mg / 250 mL (P) — D5W",
    "conc_en": "300 mg / 50 mL (C) — MD / LD — D5W",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Class III antiarrhythmic — predominantly blocks K⁺ channels, prolonging repolarization and refractory period; also has Na⁺, Ca²⁺ and β-blocking effects.",
    "side_effects": "• Hypotension\n• Bradycardia / AV block\n• QT prolongation / torsades de pointes\n• Proarrhythmia\n• Hepatic injury",
    "notes": "Clinical summary verified against official DailyMed labeling and AHA adult advanced life support guidance. Departmental Dilution and Dose/Rate remain unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Atropine",
    "group": "Chronotropes",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "Resuscitation: 0.5–1 mg every 3–5 min",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Symptomatic bradycardia\n• Bradyasystolic cardiac arrest in selected protocols\n• Muscarinic toxicity",
    "contra": "• No absolute contraindication in emergency use\n• Caution: ischemia/tachyarrhythmia",
    "monitor": "• ECG\n• HR and BP\n• Clinical response",
    "pharm": "Antimuscarinic / Anticholinergic",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Antimuscarinic → blocks vagal effects on SA/AV nodes.",
    "side_effects": "• Tachycardia\n• Dry mouth\n• Urinary retention\n• Confusion",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Calcium gluconate 10%",
    "group": "Electrolytes",
    "std": "1 g/100 cc (p/c)",
    "conc": "אמפולה ללא מיהול; בולוס איטי 10 דק׳",
    "dose": "1–2 g over 30–60 min\nMaximum rate: 1 g over 10 min",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Symptomatic hypocalcemia\n• Hyperkalemia with ECG changes\n• Selected calcium-channel blocker toxicity",
    "contra": "• Hypercalcemia\n• Neonates receiving ceftriaxone\n• Caution with cardiac glycosides",
    "monitor": "• ECG\n• Ionized/serum Ca²⁺\n• IV site\n• BP",
    "pharm": "Calcium salt",
    "std_en": "1 g / 100 mL (P/C)",
    "conc_en": "1 ampoule undiluted (P/C); slow bolus over 10 min",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Calcium salt → increases extracellular calcium availability.",
    "side_effects": "• Bradycardia/arrhythmia if rapid\n• Hypotension\n• Tissue injury with extravasation",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Dexmedetomidine (Precedex)",
    "group": "Sedation",
    "std": "200 mcg/50 cc N/S (p/c)",
    "conc": "",
    "dose": "0.2–1.5 mcg/kg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• ICU sedation of intubated/mechanically ventilated adults\n• Procedural sedation",
    "contra": "• No formal contraindications in label\n• Caution: advanced heart block, severe ventricular dysfunction, hypovolemia",
    "monitor": "• Continuous HR and BP\n• Sedation level\n• Rhythm",
    "pharm": "Selective α2-adrenergic agonist",
    "dilution": "200 mcg / 50 mL N/S (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Selective α2-agonist → sedation and sympatholysis with limited respiratory depression.",
    "side_effects": "• Bradycardia\n• Hypotension\n• Transient hypertension",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Diazepam",
    "group": "Sedation",
    "std": "אין צורך למהול; אמפולות מוכנות",
    "conc": "",
    "dose": "Slow bolus: 5–10 mg over 5 min; may repeat every 3–5 min",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Status epilepticus adjunct\n• Acute agitation/anxiety in selected settings\n• Premedication/sedation including cardioversion",
    "contra": "• Hypersensitivity\n• Acute narrow-angle glaucoma\n• Caution with opioids/respiratory depression",
    "monitor": "• RR / SpO₂\n• BP\n• Sedation/airway",
    "pharm": "Benzodiazepines",
    "dilution": "No dilution required; ready-to-use ampoules",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Benzodiazepine → potentiates GABA-A.",
    "side_effects": "• Respiratory depression\n• Hypotension\n• Excessive sedation",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Digoxin",
    "group": "Rate Control / Inotropes",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "Bolus: 0.25–0.5 mg every 6 h, up to 8–12 mcg/kg/day",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Ventricular rate control in chronic AF\n• Selected heart-failure patients",
    "contra": "• Ventricular fibrillation\n• Hypersensitivity\n• Caution: AV block/sinus-node disease, accessory pathway",
    "monitor": "• ECG / HR\n• K⁺ / Mg²⁺\n• Renal function\n• Digoxin level when indicated",
    "pharm": "Cardiac glycoside",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Cardiac glycoside → inhibits Na⁺/K⁺-ATPase; increases vagal tone.",
    "side_effects": "• Bradyarrhythmias / AV block\n• Ventricular arrhythmias\n• Nausea/visual symptoms",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Dipyrone (Optalgin)",
    "group": "Analgesics",
    "std": "1000 mg/100 cc (p/c)",
    "conc": "",
    "dose": "1000 mg over 30–60 min",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Acute moderate–severe pain\n• High fever when alternatives are unsuitable",
    "contra": "• Hypersensitivity to pyrazolones\n• Prior agranulocytosis/bone-marrow suppression\n• Significant hypotension — caution",
    "monitor": "• BP during IV use\n• Clinical response\n• CBC if clinically indicated/prolonged use",
    "pharm": "Non-opioid analgesic / Pyrazolone",
    "dilution": "1000 mg / 100 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Non-opioid pyrazolone analgesic/antipyretic.",
    "side_effects": "• Hypotension\n• Agranulocytosis\n• Anaphylaxis",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Dobutamine",
    "group": "Inotropes",
    "std": "250–500 mg/50 cc (p/c) (D5W)",
    "conc": "",
    "dose": "1–20 mcg/kg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Low cardiac output with hypoperfusion\n• Short-term inotropic support",
    "contra": "• Hypersensitivity\n• Caution: dynamic LV outflow obstruction, tachyarrhythmias",
    "monitor": "• Continuous ECG\n• BP\n• Perfusion/urine output\n• HR",
    "pharm": "β1-adrenergic agonist",
    "dilution": "250–500 mg / 50 mL (P/C) (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Predominantly β1-agonist → increases contractility and cardiac output.",
    "side_effects": "• Tachycardia\n• Ventricular ectopy/arrhythmias\n• BP changes",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Dopamine",
    "group": "Vasopressors / Inotropes",
    "std": "400 mg/500 cc (p/c)",
    "conc": "200 mg/50 cc (c)",
    "dose": "1–20 mcg/kg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Distributive shock\n• Shock due to reduced cardiac output",
    "contra": "• Pheochromocytoma\n• Correct hypovolemia/acidosis/hypoxia first\n• Caution: tachyarrhythmias",
    "monitor": "• Continuous ECG\n• BP\n• Peripheral perfusion\n• IV site/urine output",
    "pharm": "Catecholamine / dopaminergic-adrenergic agonist",
    "std_en": "400 mg / 500 mL (P/C) — D5W",
    "conc_en": "200 mg / 50 mL (C) — D5W",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Dose-dependent dopaminergic and α/β adrenergic agonist.",
    "side_effects": "• Arrhythmias\n• Tissue ischemia/extravasation injury\n• Hypertension",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Epinephrine",
    "group": "Vasopressors / Inotropes",
    "std": "",
    "conc": "4–16 mg/50 cc (c) (D5W)",
    "dose": "0.02–0.35 mcg/kg/min",
    "diluent": "D5W",
    "route": "c",
    "indications": "• Cardiac arrest\n• Anaphylaxis\n• Severe shock requiring adrenergic support",
    "contra": "• No absolute contraindication in life-threatening emergencies\n• Caution: tachyarrhythmia/ischemia",
    "monitor": "• Continuous ECG\n• BP\n• HR\n• Perfusion/lactate when indicated",
    "pharm": "α/β-adrenergic agonist",
    "dilution": "4–16 mg / 50 mL (C) (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "C",
    "mechanism": "α1/α2/β1/β2 agonist → vasoconstriction, inotropy and chronotropy.",
    "side_effects": "• Tachyarrhythmias\n• Hypertension\n• Myocardial ischemia\n• Hyperglycemia/lactate rise",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Esmolol",
    "group": "Rate Control",
    "std": "500 mg/50 ml (p/c)",
    "conc": "",
    "dose": "LD: 0.5–1.5 mg/kg bolus\nMD: 2 mcg/kg/min\nRenal failure: 1 mcg/kg/min",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Short-term control of SVT/AF ventricular rate\n• Perioperative tachycardia/hypertension",
    "contra": "• Severe sinus bradycardia\n• >1st-degree heart block without pacemaker\n• Cardiogenic shock/decompensated HF\n• Hypersensitivity",
    "monitor": "• Continuous ECG\n• HR and BP\n• Signs of HF",
    "pharm": "β1-selective blocker",
    "dilution": "500 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Ultra-short-acting β1-selective blocker.",
    "side_effects": "• Hypotension\n• Bradycardia\n• Heart block",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Fentanyl",
    "group": "Analgesics / Sedation",
    "std": "Undiluted 250 mcg/50 cc (p/c)",
    "conc": "",
    "dose": "25–200 mcg/h",
    "diluent": "Undiluted",
    "route": "p/c",
    "indications": "• Severe pain requiring opioid\n• Analgesia/sedation in monitored ICU care",
    "contra": "• Significant respiratory depression without support\n• Acute/severe bronchial asthma in unmonitored setting\n• GI obstruction/ileus\n• Hypersensitivity",
    "monitor": "• RR / SpO₂\n• BP and HR\n• Sedation/airway",
    "pharm": "Opioids / μ-opioid receptor agonist",
    "dilution": "Undiluted 250 mcg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Potent μ-opioid receptor agonist.",
    "side_effects": "• Respiratory depression\n• Bradycardia\n• Hypotension\n• Chest-wall rigidity with rapid/high-dose IV",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Furosemide",
    "group": "Diuretics",
    "std": "125–500 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Bolus: 20–240 mg\nInfusion: 1–40 mg/h",
    "diluent": "Undiluted or N/S",
    "route": "p/c",
    "indications": "• Acute pulmonary edema\n• Edema due to heart failure, renal or hepatic disease",
    "contra": "• Anuria\n• Hypersensitivity\n• Caution: severe volume/electrolyte depletion",
    "monitor": "• Urine output\n• BP\n• Na⁺/K⁺/Mg²⁺\n• Creatinine/BUN",
    "pharm": "Loop diuretic",
    "dilution": "125–500 mg / 50 mL (P/C)\nSolution: Undiluted or N/S",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Loop diuretic → inhibits Na-K-2Cl cotransporter in thick ascending limb.",
    "side_effects": "• Hypovolemia/hypotension\n• Electrolyte loss\n• Worsening renal function\n• Ototoxicity",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Heparin",
    "group": "Anticoagulation",
    "std": "25,000 units/500 cc (p/c)",
    "conc": "25,000 units/50 cc",
    "dose": "Initial rate: 20 mL/h (standard dilution)\n2 mL/h (concentrated dilution)\nSee departmental heparin correction protocol",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Treatment/prophylaxis of VTE/PE\n• Anticoagulation in selected ACS/procedural settings\n• Extracorporeal circulation/dialysis",
    "contra": "• Active uncontrolled bleeding\n• History of HIT/HITT\n• Severe thrombocytopenia\n• Hypersensitivity",
    "monitor": "• aPTT or anti-Xa per protocol\n• Platelets\n• Hb/Hct\n• Bleeding",
    "pharm": "Unfractionated heparin",
    "std_en": "25,000 units / 500 mL (P/C)",
    "conc_en": "25,000 units / 50 mL",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Potentiates antithrombin → inhibits thrombin and factor Xa.",
    "side_effects": "• Bleeding\n• HIT/HITT\n• Hyperkalemia with prolonged use",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Hydralazine",
    "group": "Vasodilators",
    "std": "שלב 1: למהול אמפולה 20 mg ב-1 ml Water for Injection\nשלב 2: למהול התמיסה ב-9 ml N/S (נפח סופי 10 ml)",
    "conc": "",
    "dose": "Bolus: 10–20 mg every 4–6 h",
    "diluent": "Water for Injection, then N/S",
    "route": "IV",
    "indications": "• Severe hypertension when IV therapy is appropriate",
    "contra": "• Hypersensitivity\n• Caution: coronary ischemia/tachycardia",
    "monitor": "• BP\n• HR\n• Clinical response",
    "pharm": "Direct arteriolar vasodilator",
    "dilution": "Step 1: Reconstitute 20 mg ampoule with 1 mL Water for Injection\nStep 2: Add 9 mL N/S (final volume 10 mL)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Direct arteriolar vasodilator → reduces systemic vascular resistance.",
    "side_effects": "• Hypotension\n• Reflex tachycardia\n• Headache/flushing",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Isuprel (Isoproterenol)",
    "group": "Chronotropes / Inotropes",
    "std": "1 mg/50 cc (p/c) (D5W)",
    "conc": "",
    "dose": "1–20 mcg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Selected severe bradycardia/heart block as temporary support\n• Selected shock/low-output states when appropriate",
    "contra": "• Tachyarrhythmias\n• Ventricular arrhythmias\n• Caution: ischemic heart disease",
    "monitor": "• Continuous ECG\n• HR and BP\n• Ischemia",
    "pharm": "Non-selective β-adrenergic agonist",
    "dilution": "1 mg / 50 mL (P/C) (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Nonselective β1/β2 agonist → increases HR/contractility and causes vasodilation.",
    "side_effects": "• Tachyarrhythmias\n• Angina/ischemia\n• Tremor",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Insulin regular (Actrapid)",
    "group": "Metabolic",
    "std": "50 units/50 cc (p/c)",
    "conc": "",
    "dose": "See departmental insulin administration protocol",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Hyperglycemia requiring IV insulin\n• DKA/HHS per protocol\n• Hyperkalemia with glucose",
    "contra": "• Hypoglycemia\n• Hypersensitivity",
    "monitor": "• Frequent glucose\n• K⁺\n• Acid-base status when relevant",
    "pharm": "Short-acting insulin",
    "dilution": "50 units / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Insulin receptor agonist → increases cellular glucose uptake and shifts K⁺ intracellularly.",
    "side_effects": "• Hypoglycemia\n• Hypokalemia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Integrilin (Eptifibatide)",
    "group": "Antiplatelets",
    "std": "LD: 2 mg/cc ampoule (p/c)\nMD: 0.75 mg/cc ampoule (p/c)\nשימו לב: אמפולות בריכוז שונה",
    "conc": "",
    "dose": "LD: 180 mcg/kg over 1–2 min\nMD: 2 mcg/kg/min\nRenal failure: 1 mcg/kg/min",
    "diluent": "Different ready concentrations; diluent not specified in source table",
    "route": "p/c",
    "indications": "• ACS in selected patients\n• PCI adjunct in selected patients",
    "contra": "• Active/recent abnormal bleeding\n• Severe uncontrolled hypertension\n• Recent major surgery or stroke\n• Hemorrhagic stroke history\n• Dialysis dependence",
    "monitor": "• Platelets\n• Hb/Hct\n• Renal function\n• Bleeding",
    "pharm": "GP IIb/IIIa inhibitor",
    "dilution": "LD ampoule: 2 mg/mL (P/C)\nMD ampoule: 0.75 mg/mL (P/C)\n⚠ Different concentrations for loading and maintenance ampoules",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "GP IIb/IIIa inhibitor → prevents fibrinogen-mediated platelet aggregation.",
    "side_effects": "• Bleeding\n• Thrombocytopenia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Isoket (Isosorbide dinitrate)",
    "group": "Vasodilators",
    "std": "20 mg/50 cc (p/c)",
    "conc": "",
    "dose": "1.2–12 mg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Severe/unstable angina\n• Acute LV failure unresponsive to standard therapy\n• Coronary spasm during PCI",
    "contra": "• Severe hypotension/hypovolemia\n• PDE-5 inhibitors or riociguat\n• HOCM/tamponade/constrictive pericarditis\n• Marked anemia",
    "monitor": "• BP\n• HR\n• Symptoms/ischemia",
    "pharm": "Organic nitrate",
    "dilution": "20 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Nitrate → nitric oxide donor causing venous > arterial vasodilation.",
    "side_effects": "• Hypotension\n• Headache\n• Reflex tachycardia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Ketamine",
    "group": "Sedation / Analgesics",
    "std": "500 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Bolus: 0.1–1 mg/kg\nInfusion: 0.2–2 mg/kg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Induction of anesthesia\n• Procedural sedation/anesthesia\n• Analgesia in selected monitored patients",
    "contra": "• Situations where significant BP elevation is hazardous\n• Hypersensitivity",
    "monitor": "• Airway / RR / SpO₂\n• BP and HR\n• Mental status",
    "pharm": "Dissociative anesthetic / NMDA antagonist",
    "dilution": "500 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "NMDA-receptor antagonist → dissociative anesthesia and analgesia.",
    "side_effects": "• Hypertension/tachycardia\n• Emergence reactions\n• Hypersalivation\n• Respiratory depression if rapid/high dose",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Labetalol",
    "group": "Antihypertensives",
    "std": "Drip: 100 mg/50 cc (p/c)\nPush: 5 mg/cc (p/c) — undiluted",
    "conc": "",
    "dose": "Bolus: 10–80 mg; may repeat every 10 min\nInfusion: 0.125–2 mg/min",
    "diluent": "Push: undiluted; infusion diluent not specified in source table",
    "route": "p/c",
    "indications": "• Severe hypertension requiring IV control",
    "contra": "• Bronchial asthma/obstructive airway disease\n• Severe bradycardia\n• >1st-degree heart block\n• Cardiogenic shock/overt HF",
    "monitor": "• BP\n• Continuous/serial HR and rhythm\n• Signs of HF",
    "pharm": "α1 / β-adrenergic blocker",
    "dilution": "Drip: 100 mg / 50 mL (P/C)\nPush: 5 mg/mL (P/C), undiluted",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "α1 + nonselective β-blocker → lowers SVR and HR.",
    "side_effects": "• Hypotension\n• Bradycardia/heart block\n• Bronchospasm\n• Rare hepatic injury",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Levosimendan",
    "group": "Inotropes / Vasodilators",
    "std": "12.5 mg/500 cc (D5W)",
    "conc": "",
    "dose": "Bolus: 6–12 mcg/kg over 10 min\nInfusion: 0.05–0.2 mcg/kg/min",
    "diluent": "D5W",
    "route": "IV",
    "indications": "• Short-term treatment of acutely decompensated severe chronic HF when inotropic support is considered appropriate",
    "contra": "• Severe hypotension/tachycardia\n• Significant mechanical obstruction to ventricular filling/outflow\n• Severe renal/hepatic impairment",
    "monitor": "• Continuous ECG\n• BP and HR\n• K⁺\n• Renal function",
    "pharm": "Calcium sensitizer / KATP-channel opener",
    "dilution": "12.5 mg / 500 mL (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Calcium sensitizer with KATP-channel opening → inotropy plus vasodilation.",
    "side_effects": "• Hypotension\n• Headache\n• Tachycardia/AF\n• Hypokalemia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Lidocaine",
    "group": "Antiarrhythmics",
    "std": "Drip: 2000 mg/500 cc\nPush: 20 mg/10 cc — undiluted",
    "conc": "",
    "dose": "Bolus: 1–1.5 mg/kg\nInfusion: 1–4 mg/min",
    "diluent": "Push: undiluted; infusion diluent not specified in source table",
    "route": "IV",
    "indications": "• Acute life-threatening ventricular arrhythmias\n• Ventricular arrhythmias during cardiac manipulation/AMI",
    "contra": "• Amide-local-anesthetic hypersensitivity\n• Stokes-Adams syndrome\n• Severe SA/AV/intraventricular block without pacing\n• WPW per label",
    "monitor": "• Continuous ECG\n• BP\n• Neurologic status",
    "pharm": "Class Ib antiarrhythmic",
    "dilution": "Drip: 2000 mg / 500 mL\nPush: 20 mg / 10 mL, undiluted",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Class Ib Na⁺-channel blocker → suppresses ventricular automaticity.",
    "side_effects": "• CNS toxicity/seizures\n• Bradycardia/heart block\n• Hypotension",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Magnesium sulfate",
    "group": "Electrolytes",
    "std": "2 g/50–100 cc",
    "conc": "",
    "dose": "Usually over 60 min\nMaximum rate: 1 g over 5 min, except during resuscitation",
    "diluent": "N/S",
    "route": "IV",
    "indications": "• Hypomagnesemia\n• Torsades de pointes / selected ventricular arrhythmias\n• Other protocol-specific indications",
    "contra": "• Severe renal impairment\n• Hypersensitivity\n• Caution: myasthenia gravis",
    "monitor": "• ECG\n• Mg²⁺ / Ca²⁺\n• Renal function\n• Reflexes/respiration at high doses",
    "pharm": "Magnesium salt",
    "dilution": "2 g / 50–100 mL",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Magnesium replacement; stabilizes cardiac membrane and modulates ion flux.",
    "side_effects": "• Hypotension\n• Bradycardia\n• Respiratory depression\n• Hypermagnesemia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": true,
    "alerts": []
  },
  {
    "name": "Metoprolol",
    "group": "Rate Control",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "IV push: 2.5–5 mg\nMaximum: 15 mg within 15 min",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Acute rate control in selected supraventricular tachyarrhythmias\n• Selected acute ischemic/hypertensive settings",
    "contra": "• Severe bradycardia\n• Significant heart block\n• Cardiogenic shock/decompensated HF\n• Hypersensitivity",
    "monitor": "• ECG\n• HR and BP\n• Signs of HF",
    "pharm": "β1-selective blocker",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "β1-selective blocker → reduces HR, AV conduction and contractility.",
    "side_effects": "• Bradycardia\n• Hypotension\n• Heart block\n• Bronchospasm",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Midazolam",
    "group": "Sedation",
    "std": "30–50 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Sedation: 0.01–0.2 mg/kg/h\nSeizures: 0.1–0.7 mg/kg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• ICU/procedural sedation\n• Induction of anesthesia\n• Acute seizure control in selected protocols",
    "contra": "• Hypersensitivity\n• Acute narrow-angle glaucoma\n• Major caution with opioids/respiratory depression",
    "monitor": "• RR / SpO₂\n• BP\n• Sedation/airway",
    "pharm": "Benzodiazepines",
    "dilution": "30–50 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Benzodiazepine → potentiates GABA-A.",
    "side_effects": "• Respiratory depression/apnea\n• Hypotension\n• Paradoxical agitation",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Milrinone",
    "group": "Inotropes / Vasodilators",
    "std": "20 mg/50 cc (p/c)",
    "conc": "",
    "dose": "LD: 50 mcg/kg over 10 min\nMD: 0.125–0.75 mcg/kg/min",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Short-term IV treatment of acute decompensated heart failure",
    "contra": "• Hypersensitivity\n• Caution: severe hypotension, ventricular arrhythmias, renal impairment",
    "monitor": "• Continuous ECG\n• BP\n• Renal function\n• K⁺",
    "pharm": "PDE-3 inhibitor",
    "dilution": "20 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "PDE-3 inhibitor → increases cAMP, producing inotropy and vasodilation.",
    "side_effects": "• Ventricular arrhythmias\n• Hypotension\n• Thrombocytopenia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Morphine",
    "group": "Analgesics / Sedation",
    "std": "30 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Bolus: 0.5–10 mg over 1–2 min\nInfusion: 1–20 mg/h\n(No maximum daily dose listed in source table)",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Severe pain requiring opioid analgesia",
    "contra": "• Significant respiratory depression\n• Severe bronchial asthma without monitoring/resuscitation\n• MAOI use within 14 days\n• GI obstruction/ileus",
    "monitor": "• RR / SpO₂\n• BP\n• Sedation/airway",
    "pharm": "Opioids / μ-opioid receptor agonist",
    "dilution": "30 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "μ-opioid receptor agonist.",
    "side_effects": "• Respiratory depression\n• Hypotension\n• Nausea/vomiting\n• Pruritus",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Nitroprusside (Nipride)",
    "group": "Vasodilators",
    "std": "50 mg/50 cc (p/c) (D5W)",
    "conc": "",
    "dose": "0.25–10 mcg/kg/min\nHeart failure: 0.25–3 mcg/kg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Hypertensive crisis\n• Acute heart failure with high afterload\n• Controlled hypotension in surgery",
    "contra": "• Compensatory hypertension (e.g. aortic coarctation/AV shunt)\n• Acute HF with low SVR\n• PDE-5 inhibitors/riociguat\n• Inadequate cerebral circulation in selected surgical use",
    "monitor": "• Continuous arterial BP preferred\n• Acid-base/lactate if prolonged/high dose\n• Renal/hepatic function\n• Cyanide/thiocyanate toxicity risk",
    "pharm": "Nitric oxide donor",
    "dilution": "50 mg / 50 mL (P/C) (D5W)\n⚠ Protect from light",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Direct nitric-oxide donor → rapid arterial and venous vasodilation.",
    "side_effects": "• Excessive hypotension\n• Cyanide/thiocyanate toxicity\n• Methemoglobinemia\n• Increased ICP",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Norepinephrine",
    "group": "Vasopressors",
    "std": "4–16 mg/50 cc (p/c) (D5W)",
    "conc": "",
    "dose": "Infusion: 0.02–0.35 mcg/kg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Severe acute hypotension\n• Vasodilatory/septic shock after adequate volume resuscitation",
    "contra": "• No absolute contraindication in life-threatening shock\n• Correct hypovolemia when possible\n• Caution: peripheral/mesenteric ischemia",
    "monitor": "• Continuous BP\n• ECG/HR\n• Peripheral perfusion\n• IV site",
    "pharm": "α1 > α2, β1 adrenergic agonist",
    "dilution": "4–16 mg / 50 mL (P/C) (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Predominantly α1 with β1 activity → vasoconstriction with modest inotropy.",
    "side_effects": "• Ischemia\n• Arrhythmias\n• Hypertension\n• Extravasation necrosis",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Pantoprazole (Controloc)",
    "group": "GI / Stress Ulcer",
    "std": "80 mg/100 cc (p/c)",
    "conc": "",
    "dose": "LD: 80 mg over 60 min\nMD: 8 mg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• IV acid suppression when oral therapy is not suitable\n• Pathologic hypersecretory states\n• Upper-GI bleed regimens may be protocol/off-label dependent",
    "contra": "• Hypersensitivity to pantoprazole/substituted benzimidazoles\n• Concomitant rilpivirine",
    "monitor": "• Clinical GI response\n• Mg²⁺ if prolonged therapy\n• IV site",
    "pharm": "Proton pump inhibitor",
    "dilution": "80 mg / 100 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Proton-pump inhibitor → irreversible gastric H⁺/K⁺-ATPase inhibition.",
    "side_effects": "• Injection-site thrombophlebitis\n• Hypomagnesemia with prolonged use\n• Acute interstitial nephritis",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Paracetamol",
    "group": "Analgesics",
    "std": "1000 mg/100 cc (p/c)",
    "conc": "",
    "dose": "Administer over 30–60 min",
    "diluent": "Undiluted",
    "route": "p/c",
    "indications": "• Mild–moderate pain\n• Fever\n• Adjunct for moderate–severe pain",
    "contra": "• Severe hepatic impairment/active severe liver disease\n• Hypersensitivity",
    "monitor": "• Total daily acetaminophen dose\n• Liver function when risk factors present",
    "pharm": "Non-opioid analgesic / Antipyretic",
    "dilution": "1000 mg / 100 mL — UNDILUTED",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Central analgesic/antipyretic; exact mechanism not fully defined.",
    "side_effects": "• Hepatotoxicity in overdose\n• Hypotension (IV, uncommon)\n• Hypersensitivity",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Phenylephrine",
    "group": "Vasopressors",
    "std": "40 mg/50 cc (c)",
    "conc": "",
    "dose": "Bolus: 50–100 mcg; slow bolus every 1–2 min up to 500 mcg maximum\nInfusion: 0.3–3 mcg/kg/min",
    "diluent": "N/S",
    "route": "c",
    "indications": "• Clinically important hypotension from vasodilation\n• Selected peri-procedural/critical-care hypotension",
    "contra": "• No absolute contraindication in emergencies in current labeling\n• Caution: severe bradycardia, ischemic disease, hypovolemia",
    "monitor": "• BP\n• HR/rhythm\n• Peripheral perfusion",
    "pharm": "Selective α1-adrenergic agonist",
    "dilution": "40 mg / 50 mL (C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "C",
    "mechanism": "Selective α1-agonist → arterial/venous vasoconstriction.",
    "side_effects": "• Reflex bradycardia\n• Hypertension\n• Ischemia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Potassium chloride (KCl)",
    "group": "Electrolytes",
    "std": "20 mEq/100 cc (p/c)",
    "conc": "10–20 mEq/50 cc (c)\n40 mEq/100 cc (c)",
    "dose": "According to departmental potassium administration protocol",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Potassium deficiency when oral replacement is not feasible",
    "contra": "• Hyperkalemia\n• Severe renal failure/potassium-retaining states\n• ⚠ Never IV push",
    "monitor": "• Continuous ECG for concentrated/high-rate replacement\n• Serum K⁺\n• Renal function\n• Acid-base status",
    "pharm": "Potassium salt",
    "std_en": "20 mEq / 100 mL (P/C)",
    "conc_en": "10–20 mEq / 50 mL (C)\n40 mEq / 100 mL (C)",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Potassium replacement → restores intracellular/extracellular K⁺ balance.",
    "side_effects": "• Fatal arrhythmia with rapid/undiluted administration\n• Hyperkalemia\n• Phlebitis",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": true,
    "alerts": []
  },
  {
    "name": "Potassium phosphate",
    "group": "Electrolytes",
    "std": "9–18 mmol/250–500 cc (p), לתת במשך 3–12 שעות",
    "conc": "15–30 mmol/150–250 cc (c), לתת במשך 2–4 שעות",
    "dose": "See dilution-specific administration time",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Hypophosphatemia requiring IV replacement",
    "contra": "• Hyperkalemia\n• Hyperphosphatemia\n• Hypercalcemia/significant hypocalcemia\n• Severe renal impairment/ESRD",
    "monitor": "• Phosphate\n• K⁺ / Ca²⁺\n• Renal function\n• ECG when indicated",
    "pharm": "Phosphate / Potassium replacement",
    "std_en": "9–18 mmol / 250–500 mL (P)\nAdminister over 3–12 h",
    "conc_en": "15–30 mmol / 150–250 mL (C)\nAdminister over 2–4 h",
    "special_dilutions": true,
    "route_en": "P/C",
    "mechanism": "Provides phosphate and potassium replacement.",
    "side_effects": "• Hyperkalemia\n• Hypocalcemia\n• Arrhythmias/cardiac arrest if rapid or insufficiently diluted",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": true,
    "alerts": []
  },
  {
    "name": "Procainamide",
    "group": "Antiarrhythmics",
    "std": "1000 mg/250 cc (p/c)\nלהחליף עירוי כל 24 שעות אם נמהל ב-N/S\nלהחליף עירוי כל 8 שעות אם נמהל ב-D5W",
    "conc": "",
    "dose": "LD: 17 mg/kg over 60 min\nUsually 1 g for 60–70 kg\n750 mg–1.5 g for 45–100 kg\nMD: 1–4 mg/min",
    "diluent": "N/S or D5W",
    "route": "p/c",
    "indications": "• Selected serious ventricular arrhythmias\n• Selected stable wide-complex tachycardia per protocol",
    "contra": "• Complete heart block without pacemaker\n• Lupus/known hypersensitivity — caution/avoid\n• Marked QT prolongation — caution",
    "monitor": "• Continuous ECG\n• QRS/QT\n• BP\n• Renal function",
    "pharm": "Class Ia antiarrhythmic",
    "dilution": "1000 mg / 250 mL (P/C)\nIf diluted in N/S: replace infusion every 24 h\nIf diluted in D5W: replace infusion every 8 h",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Class Ia Na⁺-channel blocker with K⁺-channel effects.",
    "side_effects": "• Hypotension\n• QRS/QT prolongation\n• Torsades/ventricular arrhythmia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Propofol",
    "group": "Sedation",
    "std": "אין צורך למהול; אמפולות מוכנות",
    "conc": "",
    "dose": "5–50 mcg/kg/min (maximum 100 mcg/kg/min)",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• ICU sedation of intubated, mechanically ventilated adults\n• Induction/maintenance of anesthesia\n• Procedural/MAC sedation",
    "contra": "• Hypersensitivity to propofol/components\n• Product-specific egg/soy anaphylaxis contraindication in some labels",
    "monitor": "• Continuous airway/RR/SpO₂\n• BP/HR\n• Sedation level\n• Triglycerides with prolonged infusion",
    "pharm": "IV anesthetic / GABA-A modulator",
    "dilution": "No dilution required; ready-to-use ampoules",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "GABA-A positive modulator → hypnosis/sedation.",
    "side_effects": "• Hypotension\n• Apnea/respiratory depression\n• Bradycardia\n• Propofol infusion syndrome (rare)",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Propranolol",
    "group": "Rate Control",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "IV push: 1–3 mg every 5 min up to 0.1 mg/kg maximum",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Selected supraventricular tachyarrhythmias\n• Digitalis-associated tachyarrhythmias\n• Catecholamine-mediated tachyarrhythmias",
    "contra": "• Cardiogenic shock\n• Sinus bradycardia / >1st-degree block\n• Bronchial asthma\n• Hypersensitivity",
    "monitor": "• ECG\n• HR and BP\n• Signs of bronchospasm/HF",
    "pharm": "Non-selective β-blocker",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Nonselective β1/β2 blocker.",
    "side_effects": "• Bradycardia\n• Hypotension\n• Bronchospasm\n• Heart failure worsening",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Quinidine",
    "group": "Antiarrhythmics",
    "std": "800 mg/50 cc (p/c) (D5W)",
    "conc": "",
    "dose": "0.25 mcg/kg/min",
    "diluent": "D5W",
    "route": "p/c",
    "indications": "• Selected serious atrial/ventricular arrhythmias when alternatives are unsuitable",
    "contra": "• Complete AV block without pacemaker\n• Myasthenia gravis\n• Prior quinidine/quinine thrombocytopenia\n• Marked QT prolongation — caution",
    "monitor": "• Continuous ECG\n• QT/QRS\n• BP\n• Electrolytes",
    "pharm": "Class Ia antiarrhythmic",
    "dilution": "800 mg / 50 mL (P/C) (D5W)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Class Ia Na⁺-channel blocker with K⁺-channel blockade.",
    "side_effects": "• QT prolongation/torsades\n• Hypotension\n• Cinchonism\n• Thrombocytopenia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Remifentanil",
    "group": "Analgesics / Sedation",
    "std": "5 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Bolus: 3–5 mcg\nInfusion: 0.05–0.3 mcg/kg/min",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Analgesic component of general anesthesia\n• Monitored anesthesia care in selected settings",
    "contra": "• Epidural/intrathecal administration (glycine-containing formulation)\n• Hypersensitivity to fentanyl analogs/components",
    "monitor": "• RR / SpO₂\n• BP / HR\n• Sedation/airway",
    "pharm": "Ultra-short-acting opioid",
    "dilution": "5 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Ultra-short-acting μ-opioid agonist rapidly metabolized by esterases.",
    "side_effects": "• Respiratory depression/apnea\n• Bradycardia\n• Hypotension\n• Muscle rigidity",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Rocuronium",
    "group": "Neuromuscular Blockade",
    "std": "500 mg/50 cc (p/c)",
    "conc": "",
    "dose": "Bolus: 0.6 mg/kg every 1–2 h\nor 25–50 mg for patients weighing 50–100 kg\nInfusion: 0.1–0.7 mg/kg/h",
    "diluent": "N/S",
    "route": "p/c",
    "indications": "• Rapid-sequence or routine tracheal intubation\n• Skeletal muscle relaxation during surgery/mechanical ventilation",
    "contra": "• Hypersensitivity\n• Requires adequate sedation/analgesia and ventilatory support",
    "monitor": "• TOF/neuromuscular function\n• Ventilation\n• Sedation/analgesia",
    "pharm": "Non-depolarizing neuromuscular blocker",
    "dilution": "500 mg / 50 mL (P/C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "P/C",
    "mechanism": "Nondepolarizing competitive nicotinic acetylcholine-receptor antagonist.",
    "side_effects": "• Prolonged paralysis\n• Anaphylaxis\n• Tachycardia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Succinylcholine",
    "group": "Neuromuscular Blockade",
    "std": "אין צורך למהול; לא ניתן בעירוי מתמשך",
    "conc": "",
    "dose": "Initial bolus: 0.3–1.1 mg/kg\nSubsequent doses: 0.04–0.07 mg/kg",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Facilitate tracheal intubation\n• Short-term skeletal muscle relaxation",
    "contra": "• Skeletal muscle myopathies\n• After acute phase of major burns/trauma/denervation\n• Known/suspected malignant hyperthermia susceptibility\n• Hypersensitivity",
    "monitor": "• ECG / K⁺ in high-risk patients\n• Ventilation\n• Temperature if MH concern",
    "pharm": "Depolarizing neuromuscular blocker",
    "dilution": "No dilution required; not for continuous infusion",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Depolarizing neuromuscular blocker.",
    "side_effects": "• Hyperkalemia/cardiac arrest\n• Malignant hyperthermia\n• Bradyarrhythmia\n• Prolonged apnea",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "TPA (Alteplase)",
    "group": "Thrombolytics",
    "std": "50 mg/50 cc (ממס ייעודי)",
    "conc": "",
    "dose": "See TPA administration protocol for each indication",
    "diluent": "Dedicated diluent",
    "route": "IV",
    "indications": "• Acute ischemic stroke in eligible patients\n• Acute MI in selected patients\n• Acute massive PE",
    "contra": "• Active internal bleeding\n• Recent intracranial/intraspinal surgery or serious head trauma\n• Intracranial lesion with bleeding risk\n• Severe uncontrolled hypertension\n• Additional indication-specific exclusions",
    "monitor": "• Bleeding\n• Neuro status for stroke\n• BP\n• Hb/coagulation as clinically indicated",
    "pharm": "Fibrinolytic / Recombinant tPA",
    "dilution": "50 mg / 50 mL (dedicated diluent)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Fibrinolytic → converts plasminogen to plasmin, promoting clot lysis.",
    "side_effects": "• Major/fatal bleeding\n• Intracranial hemorrhage\n• Hypersensitivity/angioedema",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Vasopressin",
    "group": "Vasopressors",
    "std": "",
    "conc": "40 units/40 cc (c)",
    "dose": "0.4–6 units/h",
    "diluent": "N/S",
    "route": "c",
    "indications": "• Vasodilatory shock with persistent hypotension despite fluids/catecholamines",
    "contra": "• Hypersensitivity to vasopressin/formulation\n• Caution: cardiac output reduction/ischemia",
    "monitor": "• BP\n• HR/rhythm\n• Peripheral/mesenteric perfusion\n• Na⁺ and urine output after discontinuation",
    "pharm": "V1 receptor agonist",
    "dilution": "40 units / 40 mL (C)",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "C",
    "mechanism": "V1-receptor agonist → vasoconstriction.",
    "side_effects": "• Decreased cardiac output\n• Brady/tachyarrhythmia\n• Ischemia\n• Hyponatremia",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  },
  {
    "name": "Verapamil",
    "group": "Rate Control / Antiarrhythmics",
    "std": "אין צורך למהול; אמפולות מוכנות",
    "conc": "",
    "dose": "Bolus: 5–10 mg over 2 min\nMay repeat after 15–30 min",
    "diluent": "Not required",
    "route": "IV",
    "indications": "• Rapid conversion of selected PSVT\n• Ventricular rate control in AF/flutter without accessory pathway",
    "contra": "• Severe hypotension/cardiogenic shock\n• 2nd/3rd-degree AV block or sick sinus without pacemaker\n• Severe LV dysfunction\n• AF/flutter with accessory pathway\n• Wide-complex VT of uncertain origin",
    "monitor": "• Continuous ECG\n• HR and BP\n• Signs of HF",
    "pharm": "Non-DHP calcium-channel blocker",
    "dilution": "No dilution required; ready-to-use ampoules",
    "special_dilutions": false,
    "std_en": "",
    "conc_en": "",
    "route_en": "IV",
    "mechanism": "Non-DHP L-type calcium-channel blocker → slows AV conduction and reduces contractility.",
    "side_effects": "• Hypotension\n• Bradycardia/AV block\n• Worsening HF",
    "notes": "Clinical essentials condensed for REVIEW from official product labeling/SmPC and, where relevant, resuscitation/cardiology guidance. Departmental Dilution and Dose/Rate are preserved unchanged.",
    "concentrated_electrolyte": false,
    "alerts": []
  }
];
